name: Deploy to GH Pages
on: 
  push:
  workflow_dispatch:

jobs:
  DepolyToGHPages:
    runs-on: ubuntu-latest

    steps:
    - name: Build and Deploy
      uses: anigieous/Deploy-Static-Website-to-GH-PAges/tree/main/Dynamic@main
      with:
        username: anigieous
        email: akak3016@gmail.com
        GITHUB_TOKEN: ${{ secrets.AKASH_TOKEN }}
