name: Deploy to GH Pages
on: 
  push:
  workflow_dispatch:

jobs:
  DepolyToGHPages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install Dependencies
      run: |
        npm install

    - name: Test the App
      run: |
        npm test

    - name: BuildGeneration
      run: |
        npm run build

    - name: Configure Git
      run: |
        git config --global user.name "Anigieous"
        git config --global user.email "akak3016@gmail.com"

    - name: Depoy
      run: |
        npm run deploy

